### PR TITLE
Revert "deleted targetApplication for Komodo IDE"

### PR DESCRIPTION
**Pull request by Defman21**
They both will works.

### CODE REVIEW

**Comment by jacoby** [comment]
Didn't see the point of the duplication, but okay.

**Comment by Defman21** [comment]
@jacoby different uuid's. So if you remove one of them - the add-on wont works for the Komodo version you removed from your install.rdf file

**Comment by Defman21** [comment]
@jacoby and don't forget to update your release (you can edit it and just update your xpi file by remove it, save draft and upload the xpi again)

**Comment by jacoby** [comment]
I have the new release up, but thanks for the reminder.

On Mon, Mar 30, 2015 at 3:08 PM, Sergey Kislyakov notifications@github.com
wrote:

> @jacoby https://github.com/jacoby and don't forget to update your
> release (you can edit it and just update your xpi file by remove it, save
> draft and upload the xpi again)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jacoby/RLangSyntax/pull/4#issuecomment-87794453.

## 

David Jacoby     jacoby.david@gmail.com

**Comment by Defman21** [comment]
Good job @jacoby! :+1:

**Pull request merged**
